Update to Python 3.14.3

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,8 +1,13 @@
 #!/bin/bash
 rebuild_venv=0
-if [ $# -gt 0 ] && { [ "$1" = "0" ] || [ "$1" = "1" ]; }; then
-	rebuild_venv="$1"
-	shift
+if [ $# -gt 0 ]; then
+	if [ "$1" = "0" ] || [ "$1" = "1" ]; then
+		rebuild_venv="$1"
+		shift
+	elif [[ "$1" != -* ]]; then
+		echo "Invalid rebuild_venv positional argument: ($1). Valid values are [0, 1]" >&2
+		exit 2
+	fi
 fi
 
 source setup_python_app.sh \
